// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znxoeyjcblgqztiboqui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpueG9leWpjYmxncXp0aWJvcXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MTg4MDcsImV4cCI6MjA3NzE5NDgwN30.FA7Wak-s_rPiU5YZSJfhZoLUK1ZZvZeP3LzFlfQ88sY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});